title: "Jekyll Test"
description: "Sito di prova"
#theme: minima   # tema standard
remote_theme: pages-themes/primer

# Impostazioni GitHub Pages
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-gfm-admonitions
