name: Build & Deploy Jekyll (custom plugins)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Installa Ruby + Bundler e usa la cache delle gem
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      # Se il sito è in /documentation: builda lì dentro
      - name: Build with Jekyll
        run: bundle exec jekyll build --source ./documentation --destination ./documentation/_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./documentation/_site
          name: jekyll-site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: jekyll-site
